# see https://hub.docker.com/_/postgres for the
# latest version of PostgreSQL

version: "3.1"

services:
  stringdb:
    image: postgres:15.4
    restart: always
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=mydatabase"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
