# see https://hub.docker.com/_/postgres for the
# latest version of PostgreSQL

version: "3.1"

services:
  database: # change service name if needed
    image: postgres:15.4
    restart: always
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=mydatabase"
    volumes:
      # ./initdb contains initialization scripts (e.g. setting up tables)
      - ./initdb:/docker-entrypoint-initdb.d
      # ./FOLDER_TO_STORE_DATA will persist the database
      - ./FOLDER_TO_STORE_DATA:/var/lib/postgresql/data
    ports:
      - 5432:5432
