name: Build and push image

on:
  push:
    branches: [ "main" ]

env: 
  REGISTRY_ADDR: ${{ secrets.REGISTRY_ADDR }}
  APPNAME: sample-flask-app
  COMMIT: ${GITHUB_SHA::7}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3
    - name: setup private registry
      run: |
        sudo tee /etc/docker/daemon.json <<EOF
        { "insecure-registries": ["$REGISTRY_ADDR" ] }
        EOF
    # TODO: setup connection to vault
    - name: build docker image
      run: docker buildx build --progress=plain --platform linux/arm64,linux/amd64 -t "$REGISTRY_ADDR/$APPNAME:$COMMIT" .
    - name: push docker image
      run: docker push "$REGISTRY_ADDR/$APPNAME:$COMMIT"


